DOMAIN = "bitvavo"
PLATFORMS = ["sensor"]

CONF_API_KEY = "api_key"
CONF_API_SECRET = "api_secret"
CONF_MARKETS = "markets"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_SOFT_CLEANUP = "soft_cleanup"
CONF_ENABLE_MARKET_SENSORS = "enable_market_sensors"
CONF_ENABLE_BALANCE_SENSORS = "enable_balance_sensors"
CONF_ENABLE_FEE_SENSORS = "enable_fee_sensors"
CONF_ENABLE_HEALTH_SENSORS = "enable_health_sensors"
CONF_ENABLE_PORTFOLIO_SENSORS = "enable_portfolio_sensors"

DEFAULT_MARKETS = "BTC-EUR,ETH-EUR"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_SOFT_CLEANUP = False
DEFAULT_ENABLE_MARKET_SENSORS = True
DEFAULT_ENABLE_BALANCE_SENSORS = True
DEFAULT_ENABLE_FEE_SENSORS = True
DEFAULT_ENABLE_HEALTH_SENSORS = True
DEFAULT_ENABLE_PORTFOLIO_SENSORS = True

BASE_URL = "https://api.bitvavo.com/v2"

SERVICE_REFRESH_DATA = "refresh_data"
SERVICE_SET_MARKETS = "set_markets"
